server:
  port: 0

logging:
  level:
    kr.wallaby.springcloud.userservice: DEBUG

spring:
  application:
    name: user-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
        web-admin-password: 1234
      path: /h2-console
  datasource:
    url: jdbc:h2:~/dev/workspace/spring-cloud/h2/cloud
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

greeting:
  message: Welcome to the Simple E-commerce...
  name: wallaby

#token:
#  expiration_time: 86400000
#  secret: user_token