server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/wallaby/dev/workspace/spring-cloud-ecommerce-config
          uri: https://github.com/wallaby83/spring-cloud-ecommerce-config.git
#          username: [my username]   # for Private repository
#          password: [my password]   # for Private repository